name: Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Archive Release
        uses: thedoctor0/zip-release@0.7.6
        with:
          type: 'zip'
          command: 'mkdir -p addons'
          filename: 'bad.multiplayer-${{ github.ref_name }}.zip'
          path: 'addons/bad.multiplayer'
      - name: Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          prerelease: true
          files: 'bad.multiplayer-${{ github.ref_name }}.zip'
