name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Upload Release
      uses: ncipollo/release-action@v1.18.0
      with:
        prerelease: true
        artifacts: 'addons/bad.multiplayer'
        tag: '${{ github.ref_name }}'
        name: 'bad.multiplayer-${{ github.ref_name }}.zip'
        token: ${{ secrets.GITHUB_TOKEN }}
