name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Publish BAD Multiplayer addon artifacts
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --release
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: addons/bad.multiplayer*
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true
